---
title: "mastertrialproto"
author: "Mingkun Wu"
date: "11/26/2020"
output: 
  html_document
---

# CODES ONLY

```{r libraries}
Sys.setenv(LANG = "en")
library(listdown)
library(ggplot2)
library(gtsummary)
library(flextable)
library(dplyr)
library(survival)
library(survminer)
library(rmarkdown)
library(plotly)
library(gapminder)
library(trelliscopejs)
library(DT)
library(knitr)
```

# COVID EXAMPLES

```{r covid-example-step1, echo=FALSE, message=FALSE, warning=FALSE}
library(listdown)
library(ggplot2)
library(tidyverse)
library(scales)
library(dplyr)
# Read in the regions data set.
regions = read.csv("COVID-regions-2021.csv", 
                    colClasses=c("character", "Date", rep("numeric", 2)))

# Creating the computational components
computational_components_covid <- list( 
  `New cases per day for each region` = ggplot(regions) + 
    geom_area(aes(Date_reported, New_cases, colour=WHO_region, fill=WHO_region), 
              stat="smooth", 
              alpha=.2, position="identity",
              method="loess", span=.1)+ labs(title = "Number of daily COVID cases by WHO region") +
    scale_y_continuous(expand = rep(0,4),labels = label_comma()) +
    scale_x_date(limits = as.Date(c("2020-01-01", "2021-03-15")),
                 expand = expansion(0),
                 label = label_date_short()),

`New cases per day for each region facet` = ggplot(regions, 
                                                   aes(x = Date_reported, y = New_cases, col = WHO_region, fill = WHO_region,
                                                                stat = "smooth",  method="loess", span=.1)) + geom_area( alpha=.5) + 
  facet_wrap(.~WHO_region) + labs(title = "Number of daily COVID cases by WHO region facet") + scale_y_continuous(expand = rep(0,4),labels = label_comma()) +
     scale_x_date(limits = as.Date(c("2020-01-01", "2021-03-15")),
                 expand = expansion(0),
                 label = label_date_short()),


`Cases against Death` = ggplot(data = regions,
       aes(x=New_cases, y=New_deaths, color = WHO_region)) + geom_point(alpha = .2) + 
    scale_x_sqrt() +
    scale_y_sqrt() +
  labs(title = "Number of COVID cases against death by WHO region"),
     

`Cases against Death facet` = ggplot(filter(regions, New_cases >= 0),
       aes(New_cases, New_deaths, colour=WHO_region)) + 
    geom_point(alpha=.2) +
    scale_x_sqrt() +
    scale_y_sqrt() +
    facet_wrap(vars(WHO_region)) +
    theme(aspect.ratio=1, legend.position="none") +
    labs(title = "Number of COVID cases against death by WHO region by facet")

)

#Save file to the disk
 saveRDS(computational_components_covid, "comp-comp_covid.rds")
 
comp_covid <- readRDS("comp-comp_covid.rds")

ld_cc_dendro(comp_covid)

```

```{r covid-example-step2, echo=FALSE, message=FALSE, warning=FALSE}
#Making a listdown object
library(listdown)
library(knitr)
ld_new <- listdown(load_cc_expr = readRDS("comp-comp_covid.rds"),
package = c("ggplot2", "tidyverse","scales"))

class(ld_new)
ld_new
```

```{r covid-example-step3, echo=FALSE, message=FALSE, warning=FALSE}
covidexample <- c(
 as.character(ld_rmarkdown_header("Covid plots",
author = "Leon",
 date = "2021")),
ld_make_chunks(ld_new))

covidexample
```

```{r covid-example-step4}
library(knitr)
library(rmarkdown)
# Write the document.
 #  writeLines(covidexample, "covid-example.Rmd")
 #  render("covid-example.Rmd",html_document())
 # system("open covid-example.html")
```

```{r covid-example-make-1, include=FALSE}
library(knitr)
knitr::opts_knit$set(unnamed.chunk.label="covid-example-stepx")
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(rmarkdown)
# Write chunks
writeLines(covidexample, "covid-example.Rmd")
render("covid-example.Rmd",html_document(), run_pandoc=FALSE, quiet=TRUE)
```

```{r covid-example-out1, results="asis", echo=FALSE}
cat(paste(readLines("covid-example.knit.md"), collapse="\n"))
```

#COVID DECORATOR EXAMPLES

```{r covid-decorator-example-step1, echo=FALSE, message=FALSE, warning=FALSE}
#Add in data and decorators, DATA ADDED IN THIS TIME
library(listdown)
library(DT)



computational_components_covid$Data <- regions
saveRDS(computational_components_covid, "comp-comp_covid.rds")

ld_new_data <- listdown(load_cc_expr = readRDS("comp-comp_covid.rds"),
package = c("ggplot2", "tidyverse","scales","DT","plotly"),
decorator = list(ggplot = ggplotly,
                 data.frame = datatable))
ld_new_data
```

```{r covid-decorator-example-step2, echo=FALSE, message=FALSE, warning=FALSE}
library(rmarkdown)
coviddecoratorexample <- c(
  as.character(ld_rmarkdown_header("covid-example")),
          ld_make_chunks(ld_new_data))

# writeLines(coviddecoratorexample, "covid-decorator-example.Rmd")
# render("covid-decorator-example.Rmd",html_document())
# system("open covid-decorator-example.html")
```

```{r coviddecoratorexamplemake1, include=FALSE}
library(knitr)
library(DT)
knitr::opts_knit$set(unnamed.chunk.label="covid-decorator-example-step2")
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(warning = FALSE)
datatable(data.frame(x = 1))
library(rmarkdown)
# Write chunks
writeLines(coviddecoratorexample, "covid-decorator-example.Rmd")
render("covid-decorator-example.Rmd",html_document(), run_pandoc=FALSE, quiet=TRUE)
```

```{r coviddecoratorexampleout1, results="asis", echo=FALSE}
cat(paste(readLines("covid-decorator-example.knit.md"), collapse="\n"))
```

# GAPMINDER EXAMPLES

```{r gapminder-example-step1, echo=FALSE, message=FALSE, warning=FALSE}

library(ggplot2)
library(gapminder)
library(listdown)
library(gapminder)
library(trelliscopejs)
library(ggplot2)
library(tidyverse)
library(DT)
library(rmarkdown)

# Load the gapminder data set.
data(gapminder)
# gapminder$country[gapminder$country == "Cote d'Ivoire"] = "CotedIvoire"

 
# Creating the computational components
comp_comp_gapminder <- list(
  `life expectancy` = ggplot( gapminder) + geom_point(aes(x = year, y = lifeExp)) + 
  xlim(1948, 2011) + ylim(10, 95) + 
  theme_bw() + 
  labs(title = "life expectancy by continent") +
  facet_wrap(~ country + continent))

#Save file to the disk
 saveRDS(comp_comp_gapminder, "comp-comp_gapminder.rds")

 
# A not very effective visualization
ld_gapminder <- listdown(load_cc_expr = readRDS("comp-comp_gapminder.rds"),
package = c("ggplot2","gapminder"))

gapminder_example <- c(
 as.character(ld_rmarkdown_header("gapminder plots",
author = "Leon",
 date = "2021")),
ld_make_chunks(ld_gapminder))

 # writeLines(gapminder_example, "gapminder-example.Rmd")
 #  render("gapminder-example.Rmd",html_document())
 #  system("open gapminder-example.html")
```

```{r gapminderexamplemake1, include=FALSE}
library(knitr)
knitr::opts_knit$set(unnamed.chunk.label="gapminder-example-step1")
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(rmarkdown)
# Write chunks
writeLines(gapminder_example, "gapminder-example.Rmd")
render("gapminder-example.Rmd",html_document(), run_pandoc=FALSE, quiet=TRUE)
```

```{r gapminderexampleout1, results="asis", echo=FALSE}
cat(paste(readLines("gapminder-example.knit.md"), collapse="\n"))
```

```{r gapminder-example-step2, echo=FALSE, message=FALSE, warning=FALSE}  
# What trelliscope would look like when we use trelliscope instead of facet
# library(ggplot2)
# library(trelliscopejs)
# library(gapminder)
# ggplot(gapminder) + geom_point(aes(x = year, y = lifeExp)) +
#   xlim(1948, 2011) + ylim(10, 95) + theme_bw() +
#   facet_trelliscope(~ country + continent, nrow = 2, ncol = 7, width = 300)

```

#GAPMINDER FUNCTION EXAMPLES GGTRE FACET_WRAP2TS FACET_TSPLOTLY

## ggtre
```{r gapminder-trellis-example-step1, echo=FALSE, message=FALSE, warning=FALSE}
# Creating the computational components, this time without the 'facet_wrap' call.
library(gapminder)

comp_comp_gapminder_trellis <- list(
  `life expectancy full` = ggplot(gapminder) + geom_point(aes(x = year, y = lifeExp)) + 
  xlim(1948, 2011) + ylim(10, 95) + 
  theme_bw() + 
  labs(title = "life expectancy by continent"))

#Save file to the disk
 saveRDS(comp_comp_gapminder_trellis, "comp-comp_gapminder_trellis.rds")
```

```{r gapminder-trellis-example-step2, echo=FALSE, message=FALSE, warning=FALSE}
library(listdown)
# Adding trelliscope call in the initial expressions, notice the description: Path ="."

ld_gapminder_trellis <- listdown(load_cc_expr = readRDS("comp-comp_gapminder_trellis.rds"),
package = c("ggplot2","gapminder", "trelliscopejs"),
decorator = list(ggplot = ggtre), 
init_expr = {
  ggtre = function(x) x + facet_trelliscope(~ country + continent,
                                           nrow = 2, ncol = 7, width = 300, path = ".")
}
)
ld_gapminder_trellis
```

```{r gapminder-trellis-example, echo=FALSE, message=FALSE, warning=FALSE}
library(rmarkdown)
gapminder_trellis_example <- c(
 as.character(ld_rmarkdown_header("gapminder plots using trelliscope",
author = "Leon",
 date = "2021")),
ld_make_chunks(ld_gapminder_trellis))

 # writeLines(gapminder_trellis_example, "gapminder_trellis-example.Rmd")
 #  render("gapminder_trellis-example.Rmd",html_document())
 #  system("open gapminder_trellis-example.html")
```

```{r gapmindertrellisexamplemake1, include=FALSE}
library(knitr)
library(DT)
knitr::opts_knit$set(unnamed.chunk.label="gapminder-trellis-example-step3")
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(rmarkdown)
# Write chunks
writeLines(gapminder_trellis_example, "gapminder_trellis-example.Rmd")
render("gapminder_trellis-example.Rmd",html_document(), run_pandoc=FALSE, quiet=TRUE)
```

```{r gapmindetrellisexampleout1, results="asis", echo=FALSE}
cat(paste(readLines("gapminder_trellis-example.knit.md"), collapse="\n"))
```

## facet_wrap2ts
```{r facetwrap2ts}  
# Created a generic function for trelliscope
# y is an ggplot object
facet_wrap2ts <- function(y){
  if (is(y$facet, "Facet") && !is(y, "FacetNull")) {
  ## get variables
  v = y$facet$vars()
  ## construct Null facet to replace it
  o = ggplot()
  facetNull = o$facet
  y$facet = facetNull
  ## construct the formula
  form = eval(parse(text=paste0("~ ", paste(v, collapse=" + "))))
  ## construct call
  c = as.call(list(quote(facet_trelliscope), form,
                   ncol = 2, path="."))
  y + eval(c)
  } else y
}

```

```{r gapminder-trellis-generic-example-step1, echo=FALSE, message=FALSE, warning=FALSE}
## Same data set as the first example, switching the decorator this time instead of adding initial expression
ld_gapminder_trellis_generic <- listdown(load_cc_expr = readRDS("comp-comp_gapminder.rds"),
package = c("ggplot2","gapminder", "trelliscopejs"),
decorator = list(ggplot = facet_wrap2ts)
)

gapminder_trellis_generic_example <- c(
 as.character(ld_rmarkdown_header("gapminder plots trelliscope generic",
author = "Leon",
 date = "2021")),
ld_make_chunks(ld_gapminder_trellis_generic))

ld_gapminder_trellis_generic
# Make the document
 # writeLines(gapminder_trellis_generic_example, "gapminder_trellis_generic-example.Rmd")
 #  render("gapminder_trellis_generic-example.Rmd",html_document())
 #  system("open gapminder_trellis_generic-example.html")
```

```{r gapminder-trellis-generic-example-make-1, include=FALSE}
library(knitr)
library(DT)
knitr::opts_knit$set(unnamed.chunk.label="gapminder-trellis-generic-example-step1")
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(warning = FALSE)
datatable(data.frame(x = 1))
library(rmarkdown)
# Write chunks
writeLines(gapminder_trellis_generic_example, "gapminder_trellis_generic-example.Rmd")
render("gapminder_trellis_generic-example.Rmd",html_document(), run_pandoc=FALSE, quiet=TRUE)
```

```{r gapminder-trellis-generic-example-out-1, results="asis", echo=FALSE}
cat(paste(readLines("gapminder_trellis_generic-example.knit.md"), collapse="\n"))
```

## facet_tsplotly
```{r facettsplotly}
# If p is an ggplot object
facet_tsplotly <- function(p, ...) {
  if (is(p$facet, "Facet") && !is(p, "FacetNull")) {
    v = p$facet$vars()
    o = ggplot()
    FacetNull = o$facet
    p$facet = FacetNull
    form = eval(parse(text=paste0("~ ", paste(v, collapse=" + "))))
    c = as.call(list(quote(facet_trelliscope), eval(parse(text=paste0("~ ", paste(v, collapse=" + ")))),
                     ncol = 2,path=".", as_plotly = TRUE))
    #the function call with the plotly argument gets evaluated 
    p + eval(c)
  }  else p
}
```

```{r gapminder-trellis-plotly-example-step1, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
## Still the same data set as the first example
ld_gapminder_trellis_plotly <- listdown(load_cc_expr = readRDS("comp-comp_gapminder.rds"),
package = c("ggplot2","gapminder", "trelliscopejs","plotly"),
decorator = list(ggplot = facet_tsplotly)
)

gapminder_trellis_plotly_example <- c(
 as.character(ld_rmarkdown_header("gapminder plots trelliscope plotly",
author = "Leon",
 date = "2021")),
ld_make_chunks(ld_gapminder_trellis_plotly))
ld_gapminder_trellis_plotly

 # writeLines(gapminder_trellis_plotly_example, "gapminder_trellis_plotly-example.Rmd")
 #  render("gapminder_trellis_plotly-example.Rmd",html_document())
 #  system("open gapminder_trellis_plotly-example.html")
```

```{r gapmindertrellisplotlyexamplemake1, include=FALSE}
library(knitr)
library(DT)
knitr::opts_knit$set(unnamed.chunk.label="gapminder-trellis-plotly-example-make-1")
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(rmarkdown)
# Write chunks
writeLines(gapminder_trellis_plotly_example, "gapminder_trellis_plotly-example.Rmd")
render("gapminder_trellis_plotly-example.Rmd",html_document(), run_pandoc=FALSE, quiet=TRUE)
```

```{r gapmindertrellisgenericexampleout1, results="asis", echo=FALSE}
cat(paste(readLines("gapminder_trellis_plotly-example.knit.md"), collapse="\n"))
```

# COVID CASE STUDY
```{r covid-trellis-step1, echo=FALSE, message=FALSE, warning=FALSE}
library(trelliscopejs)
library(listdown)
library(tidyverse)
library(rmarkdown)
#Reading in the data
covidcountries <- read.csv("WHO-COVID-19-global-data.csv",
                     colClasses=c("Date", rep("character", 3), 
                                   rep("numeric", 4))) 
names(covidcountries)[1] <- "Date_reported"

# Creating the list
comp_comp_covid_trellis <- list(
  Data = covidcountries,
  `New COVID-19 details per day for each Country` = ggplot(covidcountries) + geom_point(aes(x=Date_reported, y=New_cases, group=Country), size = 0.6) + 
  geom_line(aes(x=Date_reported, y=New_cases, group=Country), size = 0.4) +  scale_x_date(date_breaks = "3 month", date_labels =  "%b %Y") +
    theme_bw() +
  labs(title = "COVID-19 Details by Country") + 
    facet_wrap(vars(Country))
# 
#   `New COVID-19 deaths per day for each Country` = ggplot(covidcountries) + geom_point(aes(x=Date_reported, y=New_deaths, group=Country), size = 0.6) +
#   geom_line(aes(x=Date_reported, y=New_deaths, group=Country), size = 0.4) +  scale_x_date(date_breaks = "3 month", date_labels =  "%b %Y") +
#     theme_bw() +
#   labs(title = "COVID-19 Details by Country") +
#     facet_wrap(vars(Country))
  
    )


#Save file to the disk
 saveRDS(comp_comp_covid_trellis, "comp-comp_covid_trellis.rds")
 
 
# Creating the listdown package
ld_covid_trellis <- listdown(load_cc_expr = readRDS("comp-comp_covid_trellis.rds"),
package = c("ggplot2","trelliscopejs", "DT"),
decorator = list(ggplot = facet_tsplotly, 
                 data.frame = datatable)
)


# Adding a header
covid_trellis_example <- c(
 as.character(ld_rmarkdown_header("Covid plots using trelliscopeJS",
author = "Leon",
 date = "2021")),
ld_make_chunks(ld_covid_trellis))

# Making the document
 # writeLines(covid_trellis_example, "covid_trellis-example.Rmd")
 #  render("covid_trellis-example.Rmd",html_document())
 #  system("open covid_trellis-example.html")
```

```{r covid-trellis-example-make-1, include=FALSE}
library(knitr)
library(DT)
knitr::opts_knit$set(unnamed.chunk.label="covid-trellis-example-make-1")
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(warning = FALSE)
datatable(data.frame(x = 1))
library(rmarkdown)
# Write chunks
writeLines(covid_trellis_example, "covid_trellis-example.Rmd")
render("covid_trellis-example.Rmd",html_document(), run_pandoc=FALSE, quiet=TRUE)
```

```{r covid-trellis-example-out-1, results="asis", echo=FALSE}
cat(paste(readLines("covid_trellis-example.knit.md"), collapse="\n"))
```















